### ISSUE TITLE
Application startup failed when trying to run with docker

### ISSUE THREAD

**Issue by lokesh-krishna** [daya0576/beaverhabits#32]
Hello! Thank you for this wonderful project. 

Trying to run it with the default docker instructions results in `ERROR: Application startup failed. Exiting.`

Could you please guide me on what I'm missing? 

Attaching logs:

```
INFO:     Starting BeaverHabits...
INFO:     Started server process [9]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 352, in connect
    await_only(connection),
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 140, in _connect
    self._connection = await future
                       ^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 115, in run
    result = function()
             ^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 392, in connector
    return sqlite3.connect(loc, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/nicegui/ui_run_with.py", line 71, in lifespan_wrapper
    async with main_app_lifespan(app) as state:
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/beaverhabits/main.py", line 22, in lifespan
    await create_db_and_tables()
  File "/app/beaverhabits/app/db.py", line 63, in create_db_and_tables
    async with engine.begin() as conn:
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1063, in begin
    async with conn:
               ^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
    return await self.start(is_ctxmanager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 273, in start
    await greenlet_spawn(self.sync_engine.connect)
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2442, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 352, in connect
    await_only(connection),
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 140, in _connect
    self._connection = await future
                       ^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 115, in run
    result = function()
             ^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 392, in connector
    return sqlite3.connect(loc, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

ERROR:    Application startup failed. Exiting.

```

**Comment by ocean-haiyang** [comment]
> Hello! Thank you for this wonderful project.
> 
> Trying to run it with the default docker instructions results in `ERROR: Application startup failed. Exiting.`
> 
> Could you please guide me on what I'm missing?
> 
> Attaching logs:
> 
> ```
> INFO:     Starting BeaverHabits...
> INFO:     Started server process [9]
> INFO:     Waiting for application startup.
> ERROR:    Traceback (most recent call last):
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
>     self._dbapi_connection = engine.raw_connection()
>                              ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
>     return self.pool.connect()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
>     return _ConnectionFairy._checkout(self)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
>     rec = pool._do_get()
>           ^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
>     return self._create_connection()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
>     return _ConnectionRecord(self)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
>     self.__connect()
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
>     with util.safe_reraise():
>          ^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
>     raise exc_value.with_traceback(exc_tb)
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
>     self.dbapi_connection = connection = pool._invoke_creator(self)
>                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
>     return dialect.connect(*cargs, **cparams)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
>     return self.loaded_dbapi.connect(*cargs, **cparams)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 352, in connect
>     await_only(connection),
>     ^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
>     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
>     value = await result
>             ^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 140, in _connect
>     self._connection = await future
>                        ^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 115, in run
>     result = function()
>              ^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 392, in connector
>     return sqlite3.connect(loc, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> sqlite3.OperationalError: unable to open database file
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
>     async with self.lifespan_context(app) as maybe_state:
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/nicegui/ui_run_with.py", line 71, in lifespan_wrapper
>     async with main_app_lifespan(app) as state:
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
>     async with original_context(app) as maybe_original_state:
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
>     async with original_context(app) as maybe_original_state:
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
>     async with original_context(app) as maybe_original_state:
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
>     async with original_context(app) as maybe_original_state:
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
>     async with original_context(app) as maybe_original_state:
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/app/beaverhabits/main.py", line 22, in lifespan
>     await create_db_and_tables()
>   File "/app/beaverhabits/app/db.py", line 63, in create_db_and_tables
>     async with engine.begin() as conn:
>                ^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
>     return await anext(self.gen)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1063, in begin
>     async with conn:
>                ^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
>     return await self.start(is_ctxmanager=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 273, in start
>     await greenlet_spawn(self.sync_engine.connect)
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
>     result = context.throw(*sys.exc_info())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
>     return self._connection_cls(self)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
>     Connection._handle_dbapi_exception_noconnection(
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2442, in _handle_dbapi_exception_noconnection
>     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
>     self._dbapi_connection = engine.raw_connection()
>                              ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
>     return self.pool.connect()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
>     return _ConnectionFairy._checkout(self)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
>     rec = pool._do_get()
>           ^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
>     return self._create_connection()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
>     return _ConnectionRecord(self)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
>     self.__connect()
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
>     with util.safe_reraise():
>          ^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
>     raise exc_value.with_traceback(exc_tb)
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
>     self.dbapi_connection = connection = pool._invoke_creator(self)
>                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
>     return dialect.connect(*cargs, **cparams)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
>     return self.loaded_dbapi.connect(*cargs, **cparams)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 352, in connect
>     await_only(connection),
>     ^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
>     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
>     value = await result
>             ^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 140, in _connect
>     self._connection = await future
>                        ^^^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 115, in run
>     result = function()
>              ^^^^^^^^^^
>   File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 392, in connector
>     return sqlite3.connect(loc, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
> (Background on this error at: https://sqlalche.me/e/20/e3q8)
> 
> ERROR:    Application startup failed. Exiting.
> ```

Add your setup. Docker compose or YAML

**Comment by ocean-haiyang** [comment]
Add your docker compose or YAML

**Comment by lokesh-krishna** [comment]
`docker run --name beaverhabits -u $(id -u):$(id -g) -v ./beaver_data:/app/.user -p 8096:8080 daya0576/beaverhabit`

**Comment by daya0576** [comment]
@lokesh-krishna Thanks for reaching out. Could you please show us the current user and the owner of the folder `beaver_data`?

**Comment by daya0576** [comment]
Ok, that's the root cause of this permission error. 

I created wiki #31 regarding this issue, hoping it can help you. cc @ocean-haiyang

**Comment by lokesh-krishna** [comment]
Figured it out! Thanks! Setting `user: "1001"` after checking the user within the container worked!
